#!/bin/bash

if [ -z "${1}" ]; then
  echo "usage: ${0} [tasklist name] [additional options]"
  exit 1
fi

TL="${HOME}/.tasklists/${1}.json"
shift

function rj {
  # Arg1 = jq query
  jq -r "${1}" ${TL}
}

PROJECT=$(rj ".project")

A=0
LEN=$(rj ".tasks | length")
while [ "${A}" -lt "${LEN}" ]; do
  PARAMS=$(rj ".tasks[${A}].params")
  [ "${PARAMS}" == "null" ] && PARAMS=""
  task add project:${PROJECT} ${PARAMS} $@ $(rj ".tasks[${A}].description")
  let "A+=1"
done
