#! /bin/sh

xrandr --output DP-0 --mode 2560x1440 --rate 144.00
xrandr --output DP-2 --mode 2560x1440 --rate 144.00
xrandr --output DP-4 --mode 2560x1440 --rate 144.00

sxhkd &

if [ "$(wc -l ~/.polybar-monitor | awk '{print $1}')" -gt 1 ]; then
  bspc monitor $(tail -n1 ~/.polybar-monitor) -n 1 -d I III V VII IX
  bspc monitor $(head -n1 ~/.polybar-monitor) -n 2 -d II IV VI VIII X
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       any

if [ -n "$(cat ~/.picom-config | grep "yes")" ]; then
  picom --config "${HOME}/.config/picom/picom.conf" -b
fi
feh --bg-tile ~/Pictures/Wallpapers/surreal_underwater.jpg
numlockx on &

# Fix sceen blanking issue
xset dpms 0 0 0 -dpms
xset s 0 0

dropbox start

~/.config/bspwm/startup &
