#!/bin/bash

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%b %d %H:%M' > "$PANEL_FIFO" &

while :; do
  cur_battery="$(acpi | awk '{gsub(",",""); print $4+0}')"
  if [[ $cur_battery -le 20 ]]; then
    printf "BLOWBAT:%3s%%\n" "$cur_battery" > ${PANEL_FIFO}
  else
    printf "BBAT:%3s%%\n" "$cur_battery" > ${PANEL_FIFO}
  fi

  sleep 20
done &

while :; do
  wifi=$(nmcli --fields IN-USE,SSID,BARS dev wifi | grep "^*" | grep -v "SSID" | cut -c4- | tr -d "_" | sed 's/[^0-9a-zA-Z\-\ \_]/|/g' | sed 's/[\ ]*|/\ |/')

  printf "Q%s\n" "${wifi}" > ${PANEL_FIFO}

  sleep 20
done &

. ~/.config/bspwm/panel_colors

~/.config/bspwm/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
