#!/bin/bash

# Setup tmux for bg processes
tmux new -s bgprocs -d

function setDesktop() {
  sleep 0.5
  bspc desktop -f ${1}
  sleep 0.5
}

function launch() {
  tmux send-keys -t bgprocs "${1} &" C-m
  if [ -n "${2}" ]; then
    sleep ${2}
  else
    sleep 1
  fi
}

function launchWithRule() {
  if [ -z "${4}" ]; then
    ratio=0.5
  else
    ratio=${4}
  fi
  bspc rule -a ${2} -o split_dir="${3}" split_ratio=${ratio}
  launch "${1}"
}

function lockNode() {
  bspc node -g private
  sleep 0.5
}

# Setup desktop 1
setDesktop I
launch slack 3

# Setup desktop 3
setDesktop III
launch "chromium-browser"

# Setup desktop 2
setDesktop II
launch subl
lockNode
tmux new -s main -d
launchWithRule "termite -e 'tmux a -t main'" Termite south 0.6
lockNode
launchWithRule "termite -e '${HOME}/my/dotfiles/bspwm/task_panel'" Termite east 0.7
lockNode
focus termite

# Setup panel
tmux new -s panel -d
tmux send-keys -t panel '~/.config/bspwm/panel &' C-m
