#!/bin/bash

function slowKill() {
  pgrep ${1} | xargs kill
  while pgrep ${1} >/dev/null; do sleep 0.2; done
}

function setDesktop() {
  sleep 0.5
  bspc desktop -f ${1}
  sleep 0.5
}

function launch() {
  tmux send-keys -t bgprocs "${1} &" C-m
  if [ -n "${2}" ]; then
    sleep ${2}
  else
    sleep 0.2
  fi
}

function launchWithRule() {
  if [ -z "${4}" ]; then
    ratio=0.5
  else
    ratio=${4}
  fi
  bspc rule -a ${2} -o split_dir="${3}" split_ratio=${ratio}
  launch "${1}"
}

function lockNode() {
  bspc node -g private
  sleep 0.5
}
