#!/bin/bash

font="Source Code Pro-12"

W=1920
H=1080

if [ -f "~/.dmenu-resolution" ]; then
  W=$(cat ~/.dmenu-resolution | cut -d"x" -f1)
  H=$(cat ~/.dmenu-resolution | cut -d"x" -f1)
fi

dmenu_run -i -h ${H} -w ${W} -q -l 1 -class Launcher -p "                                     execute" -fn "$font" -nb "#000000" -nf "#bbbbbb" -sb "#000000" -sf "#377222"
