#!/bin/bash

font="Source Code Pro-12"

dmenu_run -i -h 1080 -w 1920 -q -l 1 -o .9 -p "                                     execute" -fn "$font" -nb "#000000" -nf "#bbbbbb" -sb "#000000" -sf "#377222"
