#!/bin/bash

function newwindow() {
  local name=${1}
  local command=${2}
  
  tmux new-window -n "${name}"
  tmux send-keys -t "${name}" "${command}" C-m
}

newwindow "snap-collisions" "dev emsdk ; source ./emsdk_env.sh ; dev snap-collisions"
newwindow "tree" "dev tree ; nvm use --delete-prefix ; util/start"
newwindow "snapviewer" "dev tree ; nvm use --delete-prefix ; cd snapviewer ; yarn start"
sleep 2
newwindow "tree logs" "dev tree ; nvm use --delete-prefix ; docker-compose logs -f tree"
