#!/bin/bash

function newwindow() {
  local name=${1}
  local command=${2}

  tmux new-window -n "${name}"
  tmux send-keys -t "${name}" "${command}" C-m
}

newwindow "snap-collisions" "dev snap-collisions"
newwindow "tree" "dev tree ; util/start"
newwindow "snapviewer" "dev tree ; cd snapviewer ; yarn start"
sleep 2
newwindow "tree logs" "dev tree ; docker-compose logs -f tree"
