#!/bin/bash

function print_usage() {
  echo "usage: ${0} [OPTIONS]"
  echo
  echo "-h|?             - print this help"
  echo "-p [PROJECT]     - The project to open (default: plingot.com)"
}

function sendcmd() {
  local target=${1}
  local command=${2}
  
  tmux send-keys -t "${target}" "${command}" C-m
}

function newwindow() {
  local name=${1}
  local command=${2}
  
  tmux new-window -n "${name}"
  sendcmd "${name}" "${command}"
}

# Reset getopts
OPTIND=1

PROJECT="plingot.com"

while getopts "h?p:" opt; do
  case "$opt" in
    h|\?)
      print_usage
      exit 0
    ;;
    
    p)
      PROJECT=${OPTARG}
    ;;
  esac
done

shift $((OPTIND-1))

newwindow "project" "dev ${PROJECT} ; nvm use --delete-prefix"
sendcmd "project" "code ."
newwindow "logs" "dev ${PROJECT} ; nvm use --delete-prefix ; yarn serve"
